/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "mukcazmeyxsnotifvucb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11a2Nhem1leXhzbm90aWZ2dWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAwMDUzMjUsImV4cCI6MjA4NTU4MTMyNX0.ZbxYKTXoo1-AD6A1MVQhQwUR9lQvSaj2FfSpZZ-vgZk"